Repository GoogleCloudPlatform/cloud-code-samples, pull requests merged in 2020-08, with the labels that each got.

#384 Shortening default project names per #379
  .templates/README.md
  .templates/template_location.json
  .templates/template_location_v2.json
Labels: cla: yes

#403 Rename `Golang: Cloud Run` template name to `Go: Cloud Run`
  .templates/template_location_v2.json
Labels: cla: yes, priority: p2, type: process

#413 Update metadata request for project id
  nodejs/nodejs-cloud-run-hello-world/index.js
Labels: cla: yes, lang: nodejs, priority: p2

#355 Update skaffold schemas from v1beta15 to v2beta4
  dotnet/dotnet-guestbook/skaffold.yaml
  dotnet/dotnet-hello-world/skaffold.yaml
  golang/go-guestbook/skaffold.yaml
  golang/go-hello-world/skaffold.yaml
  java/java-guestbook/skaffold.yaml
  java/java-hello-world/skaffold.yaml
  nodejs/nodejs-guestbook/skaffold.yaml
  nodejs/nodejs-hello-world/skaffold.yaml
  python/django/python-guestbook/skaffold.yaml
  python/django/python-hello-world/skaffold.yaml
  python/python-guestbook/skaffold.yaml
  python/python-hello-world/skaffold.yaml
Labels: cla: yes

#409 Update node to a version supported by the VS Node Debugger
  nodejs/nodejs-guestbook/src/backend/Dockerfile
  nodejs/nodejs-guestbook/src/frontend/Dockerfile
  nodejs/nodejs-hello-world/Dockerfile
Labels: cla: yes

#419 Remove redundant dockerfile entrypoint
  nodejs/nodejs-guestbook/src/backend/Dockerfile
  nodejs/nodejs-guestbook/src/frontend/Dockerfile
  nodejs/nodejs-hello-world/Dockerfile
  python/cloud-run-django-hello-world/Dockerfile
  python/cloud-run-python-hello-world/Dockerfile
  python/django/python-hello-world/src/Dockerfile
  python/python-guestbook/src/backend/Dockerfile
  python/python-guestbook/src/frontend/Dockerfile
  python/python-hello-world/src/Dockerfile
Labels: cla: yes
